### PR TITLE
Customized the LS.

### PR DESCRIPTION
**Pull request by kittaakos**
Customized the `Outline`:
Screen Shot 2019-08-21 at 20 27 29

----

Customized the hover:
screencast 2019-08-21 20-38-28

-----
Quick-fix as a code action:
screencast 2019-08-21 22-21-13

### CODE REVIEW

**Comment by kittaakos** [comment]
I consider these LS customizations as small but useful examples. If you agree, please merge. Otherwise, close the PR. Thank you!

**Comment by kittaakos** [comment]
> please merge
> close the PR

Instead of merging/closing, please give a :+1: or :-1:, I'll take care of the next steps. Thank you!

**Review by JanKoehnlein — COMMENTED** [review]
Thanks for the contribution. Sorry for taking so long with the review. Your changes all look very good. 

Unfortunately, the intention of this example is to show the minimum of things you need to do to combine Xtext, Theia and Sprotty. We'd like to keep it as simple as possible, also to keep maintenance to a minimum. Users can always dig deeper by and add more stuff when seems fit. So I am inclined to reject your contribution. Sorry for that.

**Comment by kittaakos** [comment]
> Sorry for that.

No worries.

**Pull request closed without merging**
